name: dfu-util
on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          cat COPYING
          ./autogen.sh
      - name: Enable deb-src sources
        run: |
          sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
          sudo apt update
      - name: Install dependencies
        run: |
          sudo apt-get build-dep libusb-1.0-0 dfu-util
          sudo apt-get install mingw-w64
      - name: Generate configurations
        run: |
          ./autogen.sh
          mkdir -p build
      - name: Build dfu-util
        run: |
          PKG_CONFIG_PATH=$PWD/build/lib/pkgconfig ./configure \
              --host=x86_64-pc-mingw32 --prefix=$PWD/build
          make
          make install
